<script setup lang="ts">
import { ref } from 'vue';
import { XMLAPI, AST, ASTComment, ASTCDATA, Formatter } from '@/index';

const output = ref<string[]>([]);
const isRunning = ref(false);

const sampleXml = `<book xml:lang="ja">
  <title>りんごの選び方</title>
  <section>
    <h2>選定基準</h2>
    <p>美味しいりんごを選ぶには...</p>
  </section>
  <section>
    <h2>保存方法</h2>
    <p>涼しい場所で...</p>
  </section>
</book>`;

function log(msg: string) {
  output.value.push(msg);
}

function run() {
  output.value = [];
  isRunning.value = true;
  
  // Use timeout to allow UI update
  setTimeout(() => {
    try {
      log(`Initializing XMLAPI with sample content...`);
      const api = new XMLAPI(sampleXml);

      if (api.ast) {
        const ast = api.ast;
        log("Parsing and conversion successful.");
        log("--------------------------------------------------");
        log(`Root Element: <${ast.tagName}>`);
        log(`Attribute 'xml:lang': ${ast.attr("xml:lang")}`);

        log("\n[Search Demo]");
        const titles = ast.find("title");
        titles.forEach((title) => {
          log(`Found title: ${title.text()}`);
          if (title.cst) {
            log(`  -> Source location: start=${title.cst.start}, end=${title.cst.end}`);
          }
        });

        log("\n[Incremental Update Demo]");
        const targetText = "りんごの選び方";
        const startPos = api.input.indexOf(targetText);

        if (startPos !== -1) {
          const newText = "美味しいりんごの見分け方";
          log(`Updating "${targetText}" -> "${newText}"...`);
          api.updateInput(startPos, startPos + targetText.length, newText);

          const newTitles = api.ast.find("title");
          log(`Updated title: ${newTitles[0].text()}`);
          log(`Root AST object preserved: ${api.ast === ast}`);
        }

        log("\n[AST Manipulation Demo]");
        const sections = api.ast.find("section");
        let targetSection: any = null;

        for (const section of sections) {
          const h2 = section.find("h2")[0];
          if (h2 && h2.text() === "選定基準") {
            targetSection = section;
            break;
          }
        }

        if (targetSection) {
          log("Target section found (h2='選定基準').");
          const newSectionAst = new AST("section", {}, [
            new AST("h2", {}, ["りんごを選ぶ基準"]),
            new AST("p", {}, ["基準: 大きさ, 色, 硬さ, 甘み, 酸味"]),
            new AST("p", {}, ["自分好みのものを選びましょう。"]),
          ]);

          log("Replacing node using AST construction...");
          api.replaceNode(targetSection, newSectionAst);

          if (targetSection.cst) {
            log(`Updated Section Location: start=${targetSection.cst.start}, end=${targetSection.cst.end}`);
            log("Updated Content (Snippet):");
            log(api.input.slice(targetSection.cst.start, targetSection.cst.end));
          }
        }

        log("\n[Extended Features Demo]");
        const firstSection = api.ast.find("section")[0];
        if (firstSection) {
          log("Replacing first section with Comment and CDATA...");
          const newContent = new AST("section", {}, [
            new ASTComment(" Generated by XMLAPI "),
            new ASTCDATA("Copyright <2026>"),
            new AST("p", {}, ["Updated content"]),
          ]);
          api.replaceNode(firstSection, newContent);
          
          // Re-fetch to see content (since replaceNode modifies source, identity might change if full reparse, but here we expect preservation/update)
          // Actually replaceNode triggers updateInput.
          const updatedSection = api.ast.find("section")[0];
          if (updatedSection?.cst) {
             log("Updated Section Content:");
             log(api.input.slice(updatedSection.cst.start, updatedSection.cst.end));
          }
        }
        
        log("\n[Formatter Demo]");
        const formatter = new Formatter({ indent: "  " });
        const formatted = formatter.format(api.ast);
        log("Formatted Output (Partial):");
        log(formatted.slice(0, 200) + "...");
        
        log("--------------------------------------------------");
      } else {
        log("Failed to parse.");
      }
    } catch (e: any) {
      log(`Error: ${e.message}`);
      console.error(e);
    } finally {
      isRunning.value = false;
    }
  }, 100);
}
</script>

<template>
  <div class="runner">
    <div class="controls">
      <button @click="run" :disabled="isRunning" class="run-btn">
        {{ isRunning ? 'Running...' : 'Run Code' }}
      </button>
    </div>
    <div class="console">
      <div v-if="output.length === 0" class="placeholder">
        Click "Run Code" to see the execution results.
      </div>
      <div v-else class="output-line" v-for="(line, i) in output" :key="i">
        {{ line }}
      </div>
    </div>
  </div>
</template>

<style scoped>
.runner {
  margin: 16px 0;
  border: 1px solid var(--vp-c-divider);
  border-radius: 8px;
  overflow: hidden;
  background-color: var(--vp-c-bg-alt);
}

.controls {
  padding: 8px 16px;
  border-bottom: 1px solid var(--vp-c-divider);
  background-color: var(--vp-c-bg-soft);
}

.run-btn {
  background-color: var(--vp-c-brand);
  color: white;
  border: none;
  padding: 6px 16px;
  border-radius: 4px;
  font-size: 14px;
  font-weight: 600;
  cursor: pointer;
  transition: background-color 0.2s;
}
.run-btn:hover:not(:disabled) {
  background-color: var(--vp-c-brand-dark);
}
.run-btn:disabled {
  opacity: 0.7;
  cursor: default;
}

.console {
  padding: 16px;
  font-family: var(--vp-font-family-mono);
  font-size: 13px;
  line-height: 1.5;
  color: var(--vp-c-text-1);
  min-height: 200px;
  max-height: 400px;
  overflow-y: auto;
  white-space: pre-wrap;
  background-color: #1e1e1e; /* Dark console style */
  color: #d4d4d4;
}

.placeholder {
  color: #6a737d;
  font-style: italic;
}

.output-line {
  margin-bottom: 2px;
}
</style>
