import * as fs from "fs";
import * as path from "path";
import { XMLAPI } from "./core/xml-api";
import { Formatter } from "./core/model/formatter";
import { AST, ASTCDATA, ASTComment } from "./core/ast/xml-ast";

try {
  const xmlPath = path.join(__dirname, "core/sample_01.xml");
  console.log(`Reading XML file: ${xmlPath}`);
  const xmlContent = fs.readFileSync(xmlPath, "utf8");

  // 1. Initialize XMLAPI (Parsing & CST->AST Conversion)
  const api = new XMLAPI(xmlContent);

  if (api.ast) {
    const ast = api.ast;
    console.log("Parsing and conversion successful.");
    console.log("--------------------------------------------------");
    console.log(`Root Element: <${ast.tagName}>`);
    console.log(`Attribute 'xml:lang': ${ast.attr("xml:lang")}`);

    console.log("\n[Search Demo]");
    const titles = ast.find("title");
    titles.forEach((title) => {
      console.log(`Found title: ${title.text()}`);
      
      // 2. Enhanced AST Demo (CST Mapping)
      if (title.cst) {
        console.log(`  -> Source location: start=${title.cst.start}, end=${title.cst.end}`);
      }
    });

    console.log("\n[Incremental Update Demo]");
    // Find the position of the first title content to replace it
    // Original: <title>りんごの選び方</title>
    const firstTitle = titles[0];
    // We want to replace the text content. 
    // For simplicity in this demo, we'll search string index, 
    // but in a real app we'd use cst information or selection.
    const targetText = "りんごの選び方";
    const startPos = api.input.indexOf(targetText);
    
    if (startPos !== -1) {
      const newText = "美味しいりんごの見分け方";
      console.log(`Updating "${targetText}" -> "${newText}"...`);
      
      // Perform incremental update
      api.updateInput(startPos, startPos + targetText.length, newText);
      
      // Verify AST update
      const newTitles = api.ast.find("title");
      console.log(`Updated title: ${newTitles[0].text()}`);
      
      // Verify root identity (Differential Update check)
      console.log(`Root AST object preserved: ${api.ast === ast}`);
    }

    console.log("\n[AST Manipulation Demo]");
    // Find the section with h2 "選定基準"
    const sections = api.ast.find("section");
    let targetSection: any = null;
    
    for (const section of sections) {
        const h2 = section.find("h2")[0];
        if (h2 && h2.text() === "選定基準") {
            targetSection = section;
            break;
        }
    }

    if (targetSection) {
        console.log("Target section found.");
        
        // Construct new content using AST
        const newSectionAst = new AST("section", {}, [
          new AST("h2", {}, ["りんごを選ぶ基準"]),
          new AST("p", {}, ["りんごを選ぶ際の基準には、以下のような項目があります。"]),
          new AST("ul", {}, [
            new AST("li", {}, ["大きさ"]),
            new AST("li", {}, ["色"]),
            new AST("li", {}, ["硬さ"]),
            new AST("li", {}, ["甘み"]),
            new AST("li", {}, ["酸味"]),
          ]),
          new AST("p", {}, ["これら多くの基準を考慮して、自分好みのものを選びましょう。"]),
        ]);

        console.log("Replacing node using AST construction...");
        api.replaceNode(targetSection, newSectionAst);
        
        // Due to in-place update, targetSection should reflect the new state
        if (targetSection.cst) {
             console.log(`Updated Section Location: start=${targetSection.cst.start}, end=${targetSection.cst.end}`);
             console.log("Updated Content:");
             console.log(api.input.slice(targetSection.cst.start, targetSection.cst.end));
        } else {
             console.log("Warning: CST info missing on updated node.");
        }
    } else {
        console.log("Target section not found.");
    }

    console.log("\n[Extended Features Demo]");
    const firstSection = api.ast.find("section")[0];
    if (firstSection) {
        console.log("Replacing section with Comment and CDATA...");
        const newContent = new AST("section", {}, [
            new ASTComment(" Generated by XMLAPI "),
            new ASTCDATA("Copyright <2026>"),
            new AST("p", {}, ["Updated content"])
        ]);
        api.replaceNode(firstSection, newContent);
        
        // Find updated section again
        // Note: find("section") returns all sections. We need to identify which one was updated.
        // Assuming it's still the first one (reconciliation preserves order usually)
        const updatedSection = api.ast.find("section")[0];
        if (updatedSection && updatedSection.cst) {
             console.log("Updated Section Content:");
             console.log(api.input.slice(updatedSection.cst.start, updatedSection.cst.end));
        }
    }

    console.log("\n[Formatter Demo]");
    const formatter = new Formatter({ indent: "  " });
    const formatted = formatter.format(api.ast);
    console.log("Formatted Output (first 200 chars):");
    console.log(formatted.slice(0, 200) + "...");
    
    console.log("--------------------------------------------------");
  } else {
    console.error("Failed to parse or convert XML. Is it well-formed?");
    if (api.cst && !api.cst.wellFormed) {
      console.error("The document is not well-formed.");
    }
    process.exit(1);
  }
} catch (error) {
  console.error("Error:", (error as Error).message);
  process.exit(1);
}
